In [19]:
import pandas as pd
import numpy as np
df=pd.read_csv("C:/Users/Dell/Downloads/data.csv")
print(df)
print(df.info())
print(df.shape)
print(df.head())
print(df.head(7))
print(df.tail())
print(df.tail(7))
print(df.keys())
print(df.index)
print(df.columns)
print(df.describe())
print(df.size)
print(df.memory_usage)
print(df.ndim)
print(df.agg(['sum','min']))

          Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0
1          BMW    1 Series  2011     premium unleaded (required)      300.0
2          BMW    1 Series  2011     premium unleaded (required)      300.0
3          BMW    1 Series  2011     premium unleaded (required)      230.0
4          BMW    1 Series  2011     premium unleaded (required)      230.0
...        ...         ...   ...                             ...        ...
11909    Acura         ZDX  2012     premium unleaded (required)      300.0
11910    Acura         ZDX  2012     premium unleaded (required)      300.0
11911    Acura         ZDX  2012     premium unleaded (required)      300.0
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0
11913  Lincoln      Zephyr  2006                regular unleaded      221.0

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0
1                   6.0            MANUAL   rear wheel drive              2.0
2                   6.0            MANUAL   rear wheel drive              2.0
3                   6.0            MANUAL   rear wheel drive              2.0
4                   6.0            MANUAL   rear wheel drive              2.0
...                 ...               ...                ...              ...
11909               6.0         AUTOMATIC    all wheel drive              4.0
11910               6.0         AUTOMATIC    all wheel drive              4.0
11911               6.0         AUTOMATIC    all wheel drive              4.0
11912               6.0         AUTOMATIC    all wheel drive              4.0
11913               6.0         AUTOMATIC  front wheel drive              4.0

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe
1                         Luxury,Performance      Compact    Convertible
2                    Luxury,High-Performance      Compact          Coupe
3                         Luxury,Performance      Compact          Coupe
4                                     Luxury      Compact    Convertible
...                                      ...          ...            ...
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback
11913                                 Luxury      Midsize          Sedan

       highway MPG  city mpg  Popularity   MSRP
0               26        19        3916  46135
1               28        19        3916  40650
2               28        20        3916  36350
3               28        18        3916  29450
4               28        18        3916  34500
...            ...       ...         ...    ...
11909           23        16         204  46120
11910           23        16         204  56670
11911           23        16         204  50620
11912           23        16         204  50920
11913           26        17          61  28995

[11914 rows x 16 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11914 non-null  object
 1   Model              11914 non-null  object
 2   Year               11914 non-null  int64
 3   Engine Fuel Type   11911 non-null  object
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object
 7   Driven_Wheels      11914 non-null  object
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object
 10  Vehicle Size       11914 non-null  object
 11  Vehicle Style      11914 non-null  object
 12  highway MPG        11914 non-null  int64
 13  city mpg           11914 non-null  int64
 14  Popularity         11914 non-null  int64
 15  MSRP               11914 non-null  int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.5+ MB
None
(11914, 16)
  Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0
1  BMW    1 Series  2011  premium unleaded (required)      300.0
2  BMW    1 Series  2011  premium unleaded (required)      300.0
3  BMW    1 Series  2011  premium unleaded (required)      230.0
4  BMW    1 Series  2011  premium unleaded (required)      230.0

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0
1               6.0            MANUAL  rear wheel drive              2.0
2               6.0            MANUAL  rear wheel drive              2.0
3               6.0            MANUAL  rear wheel drive              2.0
4               6.0            MANUAL  rear wheel drive              2.0

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe
1                     Luxury,Performance      Compact   Convertible
2                Luxury,High-Performance      Compact         Coupe
3                     Luxury,Performance      Compact         Coupe
4                                 Luxury      Compact   Convertible

   highway MPG  city mpg  Popularity   MSRP
0           26        19        3916  46135
1           28        19        3916  40650
2           28        20        3916  36350
3           28        18        3916  29450
4           28        18        3916  34500
  Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0
1  BMW    1 Series  2011  premium unleaded (required)      300.0
2  BMW    1 Series  2011  premium unleaded (required)      300.0
3  BMW    1 Series  2011  premium unleaded (required)      230.0
4  BMW    1 Series  2011  premium unleaded (required)      230.0
5  BMW    1 Series  2012  premium unleaded (required)      230.0
6  BMW    1 Series  2012  premium unleaded (required)      300.0

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0
1               6.0            MANUAL  rear wheel drive              2.0
2               6.0            MANUAL  rear wheel drive              2.0
3               6.0            MANUAL  rear wheel drive              2.0
4               6.0            MANUAL  rear wheel drive              2.0
5               6.0            MANUAL  rear wheel drive              2.0
6               6.0            MANUAL  rear wheel drive              2.0

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe
1                     Luxury,Performance      Compact   Convertible
2                Luxury,High-Performance      Compact         Coupe
3                     Luxury,Performance      Compact         Coupe
4                                 Luxury      Compact   Convertible
5                     Luxury,Performance      Compact         Coupe
6                     Luxury,Performance      Compact   Convertible

   highway MPG  city mpg  Popularity   MSRP
0           26        19        3916  46135
1           28        19        3916  40650
2           28        20        3916  36350
3           28        18        3916  29450
4           28        18        3916  34500
5           28        18        3916  31200
6           26        17        3916  44100
          Make   Model  Year                Engine Fuel Type  Engine HP  \
11909    Acura     ZDX  2012     premium unleaded (required)      300.0
11910    Acura     ZDX  2012     premium unleaded (required)      300.0
11911    Acura     ZDX  2012     premium unleaded (required)      300.0
11912    Acura     ZDX  2013  premium unleaded (recommended)      300.0
11913  Lincoln  Zephyr  2006                regular unleaded      221.0

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
11909               6.0         AUTOMATIC    all wheel drive              4.0
11910               6.0         AUTOMATIC    all wheel drive              4.0
11911               6.0         AUTOMATIC    all wheel drive              4.0
11912               6.0         AUTOMATIC    all wheel drive              4.0
11913               6.0         AUTOMATIC  front wheel drive              4.0

                  Market Category Vehicle Size  Vehicle Style  highway MPG  \
11909  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23
11910  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23
11911  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23
11912  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23
11913                      Luxury      Midsize          Sedan           26

       city mpg  Popularity   MSRP
11909        16         204  46120
11910        16         204  56670
11911        16         204  50620
11912        16         204  50920
11913        17          61  28995
          Make   Model  Year                Engine Fuel Type  Engine HP  \
11907    Acura     ZDX  2011     premium unleaded (required)      300.0
11908    Acura     ZDX  2011     premium unleaded (required)      300.0
11909    Acura     ZDX  2012     premium unleaded (required)      300.0
11910    Acura     ZDX  2012     premium unleaded (required)      300.0
11911    Acura     ZDX  2012     premium unleaded (required)      300.0
11912    Acura     ZDX  2013  premium unleaded (recommended)      300.0
11913  Lincoln  Zephyr  2006                regular unleaded      221.0

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
11907               6.0         AUTOMATIC    all wheel drive              4.0
11908               6.0         AUTOMATIC    all wheel drive              4.0
11909               6.0         AUTOMATIC    all wheel drive              4.0
11910               6.0         AUTOMATIC    all wheel drive              4.0
11911               6.0         AUTOMATIC    all wheel drive              4.0
11912               6.0         AUTOMATIC    all wheel drive              4.0
11913               6.0         AUTOMATIC  front wheel drive              4.0

                  Market Category Vehicle Size  Vehicle Style  highway MPG  \
11907  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23
11908  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23
11909  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23
11910  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23
11911  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23
11912  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23
11913                      Luxury      Midsize          Sedan           26

       city mpg  Popularity   MSRP
11907        16         204  56570
11908        16         204  50520
11909        16         204  46120
11910        16         204  56670
11911        16         204  50620
11912        16         204  50920
11913        17          61  28995
Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')
RangeIndex(start=0, stop=11914, step=1)
Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')
               Year    Engine HP  Engine Cylinders  Number of Doors  \
count  11914.000000  11845.00000      11884.000000     11908.000000
mean    2010.384338    249.38607          5.628829         3.436093
std        7.579740    109.19187          1.780559         0.881315
min     1990.000000     55.00000          0.000000         2.000000
25%     2007.000000    170.00000          4.000000         2.000000
50%     2015.000000    227.00000          6.000000         4.000000
75%     2016.000000    300.00000          6.000000         4.000000
max     2017.000000   1001.00000         16.000000         4.000000

        highway MPG      city mpg    Popularity          MSRP
count  11914.000000  11914.000000  11914.000000  1.191400e+04
mean      26.637485     19.733255   1554.911197  4.059474e+04
std        8.863001      8.987798   1441.855347  6.010910e+04
min       12.000000      7.000000      2.000000  2.000000e+03
25%       22.000000     16.000000    549.000000  2.100000e+04
50%       26.000000     18.000000   1385.000000  2.999500e+04
75%       30.000000     22.000000   2009.000000  4.223125e+04
max      354.000000    137.000000   5657.000000  2.065902e+06
190624
<bound method DataFrame.memory_usage of           Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0
1          BMW    1 Series  2011     premium unleaded (required)      300.0
2          BMW    1 Series  2011     premium unleaded (required)      300.0
3          BMW    1 Series  2011     premium unleaded (required)      230.0
4          BMW    1 Series  2011     premium unleaded (required)      230.0
...        ...         ...   ...                             ...        ...
11909    Acura         ZDX  2012     premium unleaded (required)      300.0
11910    Acura         ZDX  2012     premium unleaded (required)      300.0
11911    Acura         ZDX  2012     premium unleaded (required)      300.0
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0
11913  Lincoln      Zephyr  2006                regular unleaded      221.0

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0
1                   6.0            MANUAL   rear wheel drive              2.0
2                   6.0            MANUAL   rear wheel drive              2.0
3                   6.0            MANUAL   rear wheel drive              2.0
4                   6.0            MANUAL   rear wheel drive              2.0
...                 ...               ...                ...              ...
11909               6.0         AUTOMATIC    all wheel drive              4.0
11910               6.0         AUTOMATIC    all wheel drive              4.0
11911               6.0         AUTOMATIC    all wheel drive              4.0
11912               6.0         AUTOMATIC    all wheel drive              4.0
11913               6.0         AUTOMATIC  front wheel drive              4.0

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe
1                         Luxury,Performance      Compact    Convertible
2                    Luxury,High-Performance      Compact          Coupe
3                         Luxury,Performance      Compact          Coupe
4                                     Luxury      Compact    Convertible
...                                      ...          ...            ...
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback
11913                                 Luxury      Midsize          Sedan

       highway MPG  city mpg  Popularity   MSRP
0               26        19        3916  46135
1               28        19        3916  40650
2               28        20        3916  36350
3               28        18        3916  29450
4               28        18        3916  34500
...            ...       ...         ...    ...
11909           23        16         204  46120
11910           23        16         204  56670
11911           23        16         204  50620
11912           23        16         204  50920
11913           26        17          61  28995

[11914 rows x 16 columns]>
2

                                                  Make  \
sum  BMWBMWBMWBMWBMWBMWBMWBMWBMWBMWBMWBMWBMWBMWBMWB...
min                                              Acura

                                                 Model      Year  Engine HP  \
sum  1 Series M1 Series1 Series1 Series1 Series1 Se...  23951719  2953978.0
min                                           1 Series      1990       55.0

     Engine Cylinders                                  Transmission Type  \
sum           66893.0  MANUALMANUALMANUALMANUALMANUALMANUALMANUALMANU...
min               0.0                                   AUTOMATED_MANUAL

                                         Driven_Wheels  Number of Doors  \
sum  rear wheel driverear wheel driverear wheel dri...          40917.0
min                                    all wheel drive              2.0

                                          Vehicle Size  \
sum  CompactCompactCompactCompactCompactCompactComp...
min                                            Compact

                                         Vehicle Style  highway MPG  city mpg  \
sum  CoupeConvertibleCoupeCoupeConvertibleCoupeConv...       317359    235102
min                                      2dr Hatchback           12         7

     Popularity       MSRP
sum    18525212  483645697
min           2       2000

C:\Users\Dell\AppData\Local\Temp\ipykernel_240392\2905183933.py:18: FutureWarning: ['Engine Fuel Type', 'Market Category'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  print(df.agg(['sum','min']))

In [15]:
import pandas as pd
import numpy as np
n2=pd.Series({"jan":31,"feb":28,"mar":31,"apr":30,"may":31,"jun":30,"jul":31,"aug":31,"sep":30,"oct":31,"nov":30,"dec":31})
print(n2)

jan    31
feb    28
mar    31
apr    30
may    31
jun    30
jul    31
aug    31
sep    30
oct    31
nov    30
dec    31
dtype: int64

In [4]:
n3=pd.date_range('20230901',periods=35)
print(n3)

DatetimeIndex(['2023-09-01', '2023-09-02', '2023-09-03', '2023-09-04',
               '2023-09-05', '2023-09-06', '2023-09-07', '2023-09-08',
               '2023-09-09', '2023-09-10', '2023-09-11', '2023-09-12',
               '2023-09-13', '2023-09-14', '2023-09-15', '2023-09-16',
               '2023-09-17', '2023-09-18', '2023-09-19', '2023-09-20',
               '2023-09-21', '2023-09-22', '2023-09-23', '2023-09-24',
               '2023-09-25', '2023-09-26', '2023-09-27', '2023-09-28',
               '2023-09-29', '2023-09-30', '2023-10-01', '2023-10-02',
               '2023-10-03', '2023-10-04', '2023-10-05'],
              dtype='datetime64[ns]', freq='D')

In [16]:
s=pd.Series([1,2,5,np.nan,6])
print(s)

0    1.0
1    2.0
2    5.0
3    NaN
4    6.0
dtype: float64

In [1]:
import pandas as pd
import numpy as np
students_data={
    'name':['vicky','venky','nihar'],
    'reg_no':['183cs21042','183cs21044','183cs21028'],
    'address':['rammurthynagar','ramnagar','rmnagar']
}
students_data=pd.DataFrame(data=students_data,index=[1,2,3])
print(students_data)

    name      reg_no         address
1  vicky  183cs21042  rammurthynagar
2  venky  183cs21044        ramnagar
3  nihar  183cs21028         rmnagar

In [17]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
df_data={
    'FirsrName':['Aryan','Rohan','Riya','Yash','Siddhant'],
    'LastName':['Singh','Agarwal','Shah','Bhatia','Khanna'],
    'Type':['Full-Time-Employee','Intem','Full-Time-Employee','Part-Time-Employee','Full-Time-Employee'],
    'Department':['Administration','Technical','Administration','Technical','Administration'],
    'YoE':['2','3','5','7','6'],
    'Salary':['20000','5000','10000','10000','20000']
}
df_data=pd.DataFrame(data=df_data,index=[1,2,3,4,5])
df_data
pivot=df_data.pivot_table(index =['FirsrName'],
                          values =['Salary'],
                          aggfunc ='sum')
print(pivot)

          Salary
FirsrName
Aryan      20000
Riya       10000
Rohan       5000
Siddhant   20000
Yash       10000

In [5]:
import pandas as pd 
from functools import reduce
House_Predection1=pd.DataFrame({
    'SizeOfHouse':['20*20','20*30','30*40','40*20','40*50','50*20','50*30','60*30','60*20','60*60'],
    'Price':[ 2000000,340500,100000,400500,40000050,50005000,5003009,600500,6029390,601905000],
    'Gender':['male','male','female','male','female','female','female','male','male','female'],
    'GenderInNumber':[0,0,1,0,1,1,1,0,0,1],
    'Occupation':['Computer Software Engineers','Chemical Engineer','Newspaper Editor','Medical Secretary','Math Professor','Radio & TV Sports Announcer','Real Estate Sales Agents','Fashion Designer','Food & Drug Inspector','Industrial Designer'],
    'Age':['24','25','30','40','45','52','43','38','27','54'],
    'TypesOfHouses':['Apartment','Farmhouse','Farmhouse','Farmhouse','Apartment','Farmhouse','Apartment','Apartment','Apartment','Farmhouse',],
    'NoOfRoomsInHouse':['1','70','1','3','50','1','80','80','1','2']
},index=[1,2,3,4,5,6,7,8,9,10])
print(House_Predection1)
print("mapping")
def greatest_than(n):
    return n>340500
print(House_Predection1['TypesOfHouses'].map({'Apartment':'0','Farmhouse':'1'}))
#filtering=list(filter(lambda x:greater_than(x),dfs['Price']))
#print(filtering)

   SizeOfHouse      Price  Gender  GenderInNumber  \
1        20*20    2000000    male               0
2        20*30     340500    male               0
3        30*40     100000  female               1
4        40*20     400500    male               0
5        40*50   40000050  female               1
6        50*20   50005000  female               1
7        50*30    5003009  female               1
8        60*30     600500    male               0
9        60*20    6029390    male               0
10       60*60  601905000  female               1

                     Occupation Age TypesOfHouses NoOfRoomsInHouse
1   Computer Software Engineers  24     Apartment                1
2             Chemical Engineer  25     Farmhouse               70
3              Newspaper Editor  30     Farmhouse                1
4             Medical Secretary  40     Farmhouse                3
5                Math Professor  45     Apartment               50
6   Radio & TV Sports Announcer  52     Farmhouse                1
7      Real Estate Sales Agents  43     Apartment               80
8              Fashion Designer  38     Apartment               80
9         Food & Drug Inspector  27     Apartment                1
10          Industrial Designer  54     Farmhouse                2
mapping
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     0
9     0
10    1
Name: TypesOfHouses, dtype: object

In [11]:
import pandas as pd
import numpy as np
str='abcdeabcdeaabbbccddeebacdeabbbaabebdbadabdbedaebbadebadeebadefffadebfaeedbfffedfdbddddebdee'
list1=list(str)
print(list1)
series=pd.Series(list1).value_counts()
print(series.to_dict())
new_dict={
    'char':series.to_dict(),
    'occurance':series.to_dict()
}
df=pd.DataFrame(data=new_dict,index=[1,2,3,4,5,6])
print(df)
print(pd.pivot_table(df,index=['char']))

['a', 'b', 'c', 'd', 'e', 'a', 'b', 'c', 'd', 'e', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd', 'e', 'e', 'b', 'a', 'c', 'd', 'e', 'a', 'b', 'b', 'b', 'a', 'a', 'b', 'e', 'b', 'd', 'b', 'a', 'd', 'a', 'b', 'd', 'b', 'e', 'd', 'a', 'e', 'b', 'b', 'a', 'd', 'e', 'b', 'a', 'd', 'e', 'e', 'b', 'a', 'd', 'e', 'f', 'f', 'f', 'a', 'd', 'e', 'b', 'f', 'a', 'e', 'e', 'd', 'b', 'f', 'f', 'f', 'e', 'd', 'f', 'd', 'b', 'd', 'd', 'd', 'd', 'e', 'b', 'd', 'e', 'e']
{'b': 22, 'd': 21, 'e': 19, 'a': 16, 'f': 8, 'c': 5}
   char  occurance
1   NaN        NaN
2   NaN        NaN
3   NaN        NaN
4   NaN        NaN
5   NaN        NaN
6   NaN        NaN
Empty DataFrame
Columns: []
Index: []